### ISSUE TITLE
关于系统的配置

### ISSUE THREAD

**Issue by Errrneist** [hsd815/Y9000X-4K-hackintosh#1]
哈喽，请问你的电脑配置是什么呢？i7还是i9？
以及用DW网卡会遇到wifi可用但是蓝牙不可用的问题吗？因为从八代开始英特尔的蓝牙芯片开始做到CPU于是无线网卡槽就没有DW网卡蓝牙需要的USB通道了…

**Comment by daliansky** [comment]
> 哈喽，请问你的电脑配置是什么呢？i7还是i9？
> 以及用DW网卡会遇到wifi可用但是蓝牙不可用的问题吗？因为从八代开始英特尔的蓝牙芯片开始做到CPU于是无线网卡槽就没有DW网卡蓝牙需要的USB通道了…

部分主板的CNVi是可以直插m.2使用的，比如这个机型就可以，DW1820A在10.15下可完美使用，包括蓝牙。

**Comment by Errrneist** [comment]
> > 哈喽，请问你的电脑配置是什么呢？i7还是i9？
> > 以及用DW网卡会遇到wifi可用但是蓝牙不可用的问题吗？因为从八代开始英特尔的蓝牙芯片开始做到CPU于是无线网卡槽就没有DW网卡蓝牙需要的USB通道了…
> 
> 部分主板的CNVi是可以直插m.2使用的，比如这个机型就可以，DW1820A在10.15下可完美使用，包括蓝牙。

你也来啦老哥hhh

**Comment by Errrneist** [comment]
> > 哈喽，请问你的电脑配置是什么呢？i7还是i9？
> > 以及用DW网卡会遇到wifi可用但是蓝牙不可用的问题吗？因为从八代开始英特尔的蓝牙芯片开始做到CPU于是无线网卡槽就没有DW网卡蓝牙需要的USB通道了…
> 
> 部分主板的CNVi是可以直插m.2使用的，比如这个机型就可以，DW1820A在10.15下可完美使用，包括蓝牙。

哦还有 我也整了一台 十二月拿到机子开始搞 链接在这 https://github.com/Errrneist/Hackintosh-Legion-Y9000X 你如果要收录也可以收录一下

**Comment by hsd815** [comment]
> 哈喽，请问你的电脑配置是什么呢？i7还是i9？
> 以及用DW网卡会遇到wifi可用但是蓝牙不可用的问题吗？因为从八代开始英特尔的蓝牙芯片开始做到CPU于是无线网卡槽就没有DW网卡蓝牙需要的USB通道了…

我是i7的cpu，按照daliansky的教程来，蓝牙wifi一切正常。

**Comment by Errrneist** [comment]
> > 哈喽，请问你的电脑配置是什么呢？i7还是i9？
> > 以及用DW网卡会遇到wifi可用但是蓝牙不可用的问题吗？因为从八代开始英特尔的蓝牙芯片开始做到CPU于是无线网卡槽就没有DW网卡蓝牙需要的USB通道了…
> 
> 我是i7的cpu，按照daliansky的教程来，蓝牙wifi一切正常。

可以 话说如果有时间的话可以在repo放一下安装用USB的EFI吗？我本身有另外一个机子的安装盘这样换一下比较方便

**Comment by hsd815** [comment]
> > > 哈喽，请问你的电脑配置是什么呢？i7还是i9？
> > > 以及用DW网卡会遇到wifi可用但是蓝牙不可用的问题吗？因为从八代开始英特尔的蓝牙芯片开始做到CPU于是无线网卡槽就没有DW网卡蓝牙需要的USB通道了…
> > 
> > 
> > 我是i7的cpu，按照daliansky的教程来，蓝牙wifi一切正常。
> 
> 可以 话说如果有时间的话可以在repo放一下安装用USB的EFI吗？我本身有另外一个机子的安装盘这样换一下比较方便

不好意思，原USB EFI文件我已经丢失了，我使用的是Len‘s的硬盘映像，黑果小兵的应该也可以的，集显ig-platform-id要设置成0x12345678才能正常安装进系统，其他好像没什么要注意的了

**Comment by Errrneist** [comment]
🉑️
