### ISSUE TITLE
用Clover引导 睡眠后唤醒屏幕不亮

### ISSUE THREAD

**Issue by bluezsd** [hsd815/Y9000X-4K-hackintosh#10]
用Clover引导，能正常睡眠，电源键一闪一闪，按电源键唤醒电源键常亮了，但是屏幕不亮，按键盘其他按键也没有反应。这个怎么解决呀？你们的睡眠正常不？
OC下没测试，不知道是不是正常的。

**Comment by hsd815** [comment]
> 用Clover引导，能正常睡眠，电源键一闪一闪，按电源键唤醒电源键常亮了，但是屏幕不亮，按键盘其他按键也没有反应。这个怎么解决呀？你们的睡眠正常不？
> OC下没测试，不知道是不是正常的。

OC下测试正常

**Comment by bluezsd** [comment]
> > 用Clover引导，能正常睡眠，电源键一闪一闪，按电源键唤醒电源键常亮了，但是屏幕不亮，按键盘其他按键也没有反应。这个怎么解决呀？你们的睡眠正常不？
> > OC下没测试，不知道是不是正常的。
> 
> OC下测试正常

你的在Clover下也是这样吗？看来得学着用OC了，以后OC是主流，不知道什么时候会有OC的可视化配置工具。

**Comment by hsd815** [comment]
> > > 用Clover引导，能正常睡眠，电源键一闪一闪，按电源键唤醒电源键常亮了，但是屏幕不亮，按键盘其他按键也没有反应。这个怎么解决呀？你们的睡眠正常不？
> > > OC下没测试，不知道是不是正常的。
> > 
> > 
> > OC下测试正常
> 
> 你的在Clover下也是这样吗？看来得学着用OC了，以后OC是主流，不知道什么时候会有OC的可视化配置工具。

你clover加入了更名补丁了没有。这个睡眠要配合更名补丁

**Comment by bluezsd** [comment]
> > > > 用Clover引导，能正常睡眠，电源键一闪一闪，按电源键唤醒电源键常亮了，但是屏幕不亮，按键盘其他按键也没有反应。这个怎么解决呀？你们的睡眠正常不？
> > > > OC下没测试，不知道是不是正常的。
> > > 
> > > 
> > > OC下测试正常
> > 
> > 
> > 你的在Clover下也是这样吗？看来得学着用OC了，以后OC是主流，不知道什么时候会有OC的可视化配置工具。
> 
> 你clover加入了更名补丁了没有。这个睡眠要配合更名补丁

我用了你的EFI，没有另外去加更名补丁，要加哪个更名补丁呢？

**Comment by hsd815** [comment]
`<dict>
				<key>Comment</key>
				<string>SSDT-GPRW: Change GPRW to XPRW</string>
				<key>Count</key>
				<integer>0</integer>
				<key>Enabled</key>
				<true/>
				<key>Find</key>
				<data>R1BSVwI=</data>
				<key>Limit</key>
				<integer>0</integer>
				<key>Mask</key>
				<data></data>
				<key>OemTableId</key>
				<data></data>
				<key>Replace</key>
				<data>WFBSVwI=</data>
				<key>ReplaceMask</key>
				<data></data>
				<key>Skip</key>
				<integer>0</integer>
				<key>TableLength</key>
				<integer>0</integer>
				<key>TableSignature</key>
				<data></data>
			</dict>`
这是oc的config的代码，重命名了 GPRW为XPRW。你自己换成clover 的config代码

**Comment by bluezsd** [comment]
好的，我试试

**Comment by hsd815** [comment]
> 好的，我试试

请问正常了吗？正常的话这个issue就关闭了

**Comment by bluezsd** [comment]
可以了。

**Comment by xuejinwei** [comment]
@bluezsd 我也遇到了和楼主一样的问题，睡眠唤醒不了，请问你clover怎么配置的，如何加入更名补丁的，我尝试这做了，没有用，不知道是不是配置的不对
