### ISSUE TITLE
OC 0.5.3 DW1560 蓝牙失效

### ISSUE THREAD

**Issue by wangwbwwb** [hsd815/Y9000X-4K-hackintosh#12]
**DW1560 蓝牙失效**，无线可以，ram2和ram3都不行，请问有什么地方需要配置的么

另外，能否说明一下acpi里面文件的作用吗，有些不配到config里面都可以，好像没什么影响

**Comment by hsd815** [comment]
> **DW1560 蓝牙失效**，无线可以，ram2和ram3都不行，请问有什么地方需要配置的么
> 
> 另外，能否说明一下acpi里面文件的作用吗，有些不配到config里面都可以，好像没什么影响

* 其他网卡没有用过，需要你自己配置驱动，apci里面没有配置跟无线网卡有关的补丁或者更名，config里面跟无线网卡有关的地方是，1. Boot参数；2. 设备properties。

* OC的Acpi里面并没有完全开启，有些东西测试了一下没结果还是放在里面了，但是enable是关闭状态
