### ISSUE TITLE
videopro hevc显示没有激活

### ISSUE THREAD

**Issue by wghemail** [hsd815/Y9000X-4K-hackintosh#13]
videopro hevc显示没有激活，显卡配置是不是没完全设好呢，用了你的Clover efi，没改显卡部分

**Comment by hsd815** [comment]
> videopro hevc显示没有激活，显卡配置是不是没完全设好呢，用了你的Clover efi，没改显卡部分

确实会显示没有激活，但是据有些网友说，这个测试不是很准确，我个人在使用的时候播放4k视频，hevc是正常的，跟Windows无差，你可以测试一下，正常使用有没有问题

**Comment by wghemail** [comment]
inna播放256 10bit视频，显示硬解了，看来确实是video pro的问题了！
另外，1820a冷启动无法蓝牙，睡眠后蓝牙经常无法使用的问题，您那边解决了吗？谢谢

**Comment by hsd815** [comment]
> inna播放256 10bit视频，显示硬解了，看来确实是video pro的问题了！
> 另外，1820a冷启动无法蓝牙，睡眠后蓝牙经常无法使用的问题，您那边解决了吗？谢谢

网友建议换成稳定版的驱动试试
