### ISSUE TITLE
FHD屏幕的版本能直接用这个EFI吗

### ISSUE THREAD

**Issue by leogcry22** [hsd815/Y9000X-4K-hackintosh#16]
能直接用还是需要修改部分设置？

**Comment by bluezsd** [comment]
可以用，我的就是FHD屏幕的版本

**Comment by xuejinwei** [comment]
@leogcry22 @bluezsd 问一下，你们的1080P 的屏幕用的正常吗？ 我的睡眠后唤醒不了，感觉是屏幕点不亮的问题，风扇是转的。你们的bios是什么版本了，我怀疑bios版本问题了
