### ISSUE TITLE
opencore 默认启动磁盘丢失触控板后如何恢复

### ISSUE THREAD

**Issue by wangwbwwb** [hsd815/Y9000X-4K-hackintosh#17]
**opencore如果使用启动磁盘功能选择默认启动磁盘进入系统有可能会丢失声音驱动和触控板驱动**

通过引导界面进去也没有触控板，请问如何恢复

**Comment by hsd815** [comment]
> **opencore如果使用启动磁盘功能选择默认启动磁盘进入系统有可能会丢失声音驱动和触控板驱动**
> 
> 通过引导界面进去也没有触控板，请问如何恢复

清空nvram试试，我一般 是进recovery，从那里面选择默认启动磁盘，就不会有这个问题。。

**Comment by hsd815** [comment]
> **opencore如果使用启动磁盘功能选择默认启动磁盘进入系统有可能会丢失声音驱动和触控板驱动**
> 
> 通过引导界面进去也没有触控板，请问如何恢复

仅供参考，里面有什么bug我也不清楚

**Comment by wangwbwwb** [comment]
> > **opencore如果使用启动磁盘功能选择默认启动磁盘进入系统有可能会丢失声音驱动和触控板驱动**
> > 通过引导界面进去也没有触控板，请问如何恢复
> 
> 清空nvram试试，我一般 是进recovery，从那里面选择默认启动磁盘，就不会有这个问题。。

好的，我试一试，非常感谢
