### ISSUE TITLE
触控板驱动需要额外的操作吗？我使用这个EFI安装，触控板无法正常驱动

### ISSUE THREAD

**Issue by WangRicky** [hsd815/Y9000X-4K-hackintosh#2]

**Comment by hsd815** [comment]
> _No description provided._
我之前15系统是可以使用触控板的，但是重新安装了一次catalina之后也不能用了。精力有限也没找具体什么原因，现在在用mojave，14的系统触控板没问题。

**Comment by WangRicky** [comment]
> > _No description provided._
> > 我之前15系统是可以使用触控板的，但是重新安装了一次catalina之后也不能用了。精力有限也没找具体什么原因，现在在用mojave，14的系统触控板没问题。

我现在也使用的是mojave，触控板无法正常使用，这样的情况下该如何定位问题

**Comment by Errrneist** [comment]
> > _No description provided._
> > 我之前15系统是可以使用触控板的，但是重新安装了一次catalina之后也不能用了。精力有限也没找具体什么原因，现在在用mojave，14的系统触控板没问题。

试试看VoodooPS2Controller

**Comment by hsd815** [comment]
> > > _No description provided._
> > > 我之前15系统是可以使用触控板的，但是重新安装了一次catalina之后也不能用了。精力有限也没找具体什么原因，现在在用mojave，14的系统触控板没问题。
> 
> 我现在也使用的是mojave，触控板无法正常使用，这样的情况下该如何定位问题

现在Open Core引导两个系统下触控板都正常了

**Comment by wuweijavadeveloper** [comment]
我也是clover加14，触摸板不能用，请问你是如何解决的呢
