### ISSUE TITLE
兄弟现在状态停滞，是否已经满足个人需求不再修复了？

### ISSUE THREAD

**Issue by hx2nn** [hsd815/Y9000X-4K-hackintosh#20]
兄弟已经连续几日没有新得进度了，希望进一步完善本机型，基本上每日多次上来看。感谢

**Comment by hsd815** [comment]
> 兄弟已经连续几日没有新得进度了，希望进一步完善本机型，基本上每日多次上来看。感谢

现在最重要的声音问题无解
其次FN热键可以在系统里面设置其他组合快捷键
最后的HDMI问题暂时没有设备测试，自己也没有这个需求，还请各位朋友自行完善。。
