### ISSUE TITLE
clover安装mojave时过程中提示 macos未能正确安装，更新固件时发生错误

### ISSUE THREAD

**Issue by wuweijavadeveloper** [hsd815/Y9000X-4K-hackintosh#23]
一开始clover安装10.15成功了，但是没有触摸板驱动。因为看不明白oc，所以准备clover+10.14，遇到安装包损坏的问题改时间解决了，但是安装过程中又弹出未能正常安装的提示。真心心累啊，重试和抹盘已经N次了，楼主求教这个问题的解决方法

**Comment by hsd815** [comment]
> 一开始clover安装10.15成功了，但是没有触摸板驱动。因为看不明白oc，所以准备clover+10.14，遇到安装包损坏的问题改时间解决了，但是安装过程中又弹出未能正常安装的提示。真心心累啊，重试和抹盘已经N次了，楼主求教这个问题的解决方法

正常安装应该没问题，我没遇到过这个问题。百度一下这个问题看看有没有解决办法。是不是你开启了什么更新选项？

**Comment by wuweijavadeveloper** [comment]
今天重新安装成功了,但是触摸板不能用,我的是clover+mojave,请问是我什么地方没配置好吗
