### ISSUE TITLE
FN热键

### ISSUE THREAD

**Issue by Errrneist** [hsd815/Y9000X-4K-hackintosh#3]
我记得FN热键可以靠DSDT EC _Q14, _Q15 patch来解决，我还没拿到机子，也许值得一试？

**Comment by hsd815** [comment]
> 我记得FN热键可以靠DSDT EC _Q14, _Q15 patch来解决，我还没拿到机子，也许值得一试？

这个感觉不重要所以没花时间弄XD。声音是真的没办法，linux下也有图标没声音。

**Comment by Errrneist** [comment]
> > 我记得FN热键可以靠DSDT EC _Q14, _Q15 patch来解决，我还没拿到机子，也许值得一试？
> 
> 这个感觉不重要所以没花时间弄XD。声音是真的没办法，linux下也有图标没声音。

VoodooHDA也不行？那可能需要后续BIOS更新了...

**Comment by XuToTo** [comment]
Hi，想请问一下续航如何？会不会出现电池损耗呢？

**Comment by wuweijavadeveloper** [comment]
大佬请问下这个屏蔽pm981指的是macos单方面屏蔽吗?我想装双系统,在原有的win系统中还能使用981吗

**Comment by hsd815** [comment]
> 大佬请问下这个屏蔽pm981指的是macos单方面屏蔽吗?我想装双系统,在原有的win系统中还能使用981吗

win可以用的，clover可以直接引导，就是mac认不出来这个硬盘

**Comment by hsd815** [comment]
> Hi，想请问一下续航如何？会不会出现电池损耗呢？

我都是连接电源用的，偶尔断电用感觉续航稍微比win好一点吧，但是也不行。

**Comment by hx2nn** [comment]
雷电转hdmi一直不好用，这个我真的很需要，不知道能否解决？我现在是clover引导，有必要更换么？
另我的网络正常但是没有解锁支持的选项：是手表还没支持么？
再就是一个基础问题：我如何在已经安装的系统上更新你的efi（给个教程链接就行）

**Comment by hsd815** [comment]
> 雷电转hdmi一直不好用，这个我真的很需要，不知道能否解决？我现在是clover引导，有必要更换么？
> 另我的网络正常但是没有解锁支持的选项：是手表还没支持么？
> 再就是一个基础问题：我如何在已经安装的系统上更新你的efi（给个教程链接就行）

首先你看系统报告lwifi那一项里面有没有`apple watch自动解锁：支持` 如果这个都没有的话你的驱动选择有问题，启动参数里面你要选择brcmfx-driver=2，然后device properties里面选择这个pci14e4,43a3。

**Comment by hx2nn** [comment]
真的太感谢了，按照你的方法我成功的开启了apple watch自动解锁。让我对接下来的工作充满信心。
同时：可否再帮忙说明下声音外放的解决方法以及我的电池一直显示65%。
另：我的系统还是clover启动，不太会修改成oc启动，接下来的你的更新efi我是否用不了？

**Comment by hsd815** [comment]
> 真的太感谢了，按照你的方法我成功的开启了apple watch自动解锁。让我对接下来的工作充满信心。
> 同时：可否再帮忙说明下声音外放的解决方法以及我的电池一直显示65%。
> 另：我的系统还是clover启动，不太会修改成oc启动，接下来的你的更新efi我是否用不了？

扬声器个人没办法解决，电池的话你看看你的kexts里面有没有`apcibatterymanager.kext`，没有的话加上这个驱动，clover没问题就继续用clover吧 ，目前clover解决不了的问题OC也解决不了
