### ISSUE TITLE
readme中的cfg lock解锁后的教程地址是不是忘记写了

### ISSUE THREAD

**Issue by WangRicky** [hsd815/Y9000X-4K-hackintosh#34]

**Comment by hsd815** [comment]
后面Opencore教程里面有的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WangRicky <notifications@github.com&gt;
发送时间: 2020年5月28日 10:39
收件人: hsd815/Y9000X-4K-hackintosh <Y9000X-4K-hackintosh@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[hsd815/Y9000X-4K-hackintosh] readme中的cfg lock解锁后的教程地址是不是忘记写了 (#34)
