### ISSUE TITLE
如何用oc更换clover引导

### ISSUE THREAD

**Issue by hx2nn** [hsd815/Y9000X-4K-hackintosh#6]
是否直接加载efi分区，把oc文件夹放入dfi文件夹中即可，在开机选项总能看到oc么？小白请多指教

**Comment by hx2nn** [comment]
现在clover刚刚弄明白系统也基本上稳定，大神是否可以继续更新相关配置文件，要不我跟不上。。想紧跟你的步伐，无奈opencover如何更换我都不知道，请求下：是否可以继续更新clover启动相关配置

**Comment by hx2nn** [comment]
电池的话你看看你的kexts里面有没有apcibatterymanager.kext，没有的话加上这个驱动,我里面有这个，我也重新替换后重新启动了，还是固定在65%

**Comment by hsd815** [comment]
> 是否直接加载efi分区，把oc文件夹放入dfi文件夹中即可，在开机选项总能看到oc么？小白请多指教


> 电池的话你看看你的kexts里面有没有apcibatterymanager.kext，没有的话加上这个驱动,我里面有这个，我也重新替换后重新启动了，还是固定在65%

我没有遇到过这样的问题，你是用的这个efi吗？加入ssdt补丁了吗？你复制efi/oc/acpi/文件夹下带有SBRP00的aml文件到efi/clover/acpi/patched/目录下面试试

**Comment by hsd815** [comment]
> 电池的话你看看你的kexts里面有没有apcibatterymanager.kext，没有的话加上这个驱动,我里面有这个，我也重新替换后重新启动了，还是固定在65%

加入这个`SSDT-PLUG-_SB.PR00.aml`到clover/acpi/patched

**Comment by bluezsd** [comment]
我也想更换为OC引导，用Bootice添加了EFI/OC/OpenCore.efi启动项后，启动时显示一秒钟左右就自动引导Windows系统了，但是应该自动屏蔽了PM981硬盘的，所以启动Windows直接卡死。如何设置默认启动Mac的磁盘呢？

**Comment by hsd815** [comment]
> 我也想更换为OC引导，用Bootice添加了EFI/OC/OpenCore.efi启动项后，启动时显示一秒钟左右就自动引导Windows系统了，但是应该自动屏蔽了PM981硬盘的，所以启动Windows直接卡死。如何设置默认启动Mac的磁盘呢？

开机狂按esc键进系统用启动磁盘功能改成默认mac启动，或者直接修改config `timeout=5`

**Comment by hx2nn** [comment]
> > 电池的话你看看你的kexts里面有没有apcibatterymanager.kext，没有的话加上这个驱动,我里面有这个，我也重新替换后重新启动了，还是固定在65%
> 
> 加入这个`SSDT-PLUG-_SB.PR00.aml`到clover/acpi/patched

你的efi里面没有找到这个文件？

**Comment by hx2nn** [comment]
> > 电池的话你看看你的kexts里面有没有apcibatterymanager.kext，没有的话加上这个驱动,我里面有这个，我也重新替换后重新启动了，还是固定在65%
> 
> 加入这个`SSDT-PLUG-_SB.PR00.aml`到clover/acpi/patched

要加入后重新启动还是不行，一直显示65%

**Comment by hx2nn** [comment]
> 我也想更换为OC引导，用Bootice添加了EFI / OC / OpenCore.efi启动项后，启动时显示一秒钟左右就自动启动Windows系统了，但是应该自动屏蔽了PM981硬盘的，所以启动Windows直接卡死。如何设置重置启动Mac的磁盘呢？

请问是在windows里面，把efi里面的EFI / OC / OpenCore.efi加入？原来安装的mac系统需要重新安装么？想跟上脚步无奈知识很少

**Comment by hsd815** [comment]
> > 我也想更换为OC引导，用Bootice添加了EFI / OC / OpenCore.efi启动项后，启动时显示一秒钟左右就自动启动Windows系统了，但是应该自动屏蔽了PM981硬盘的，所以启动Windows直接卡死。如何设置重置启动Mac的磁盘呢？
> 
> 请问是在windows里面，把efi里面的EFI / OC / OpenCore.efi加入？原来安装的mac系统需要重新安装么？想跟上脚步无奈知识很少

不需要，记得开机狂按esc键进系统用启动磁盘功能改成默认mac启动，或者直接修改config timeout=5

**Comment by hx2nn** [comment]
> > > 我也想替换为OC引导，用Bootice添加了EFI / OC / OpenCore.efi启动项后，启动时显示一秒钟左右就自动启动Windows系统了，但是应该自动屏蔽了PM981硬盘的，所以启动Windows直接卡死。如何设置重置启动Mac的磁盘呢？
> > 
> > 
> > 请问是在windows里面，把efi里面的EFI / OC / OpenCore.efi加入？原来安装的mac系统需要重新安装么？想跟上脚步无奈知识很少
> 
> 不需要，记得开机狂按esc键进系统使用启动磁盘功能改成默认的mac启动，或者直接修改config timeout = 5

**您的意思是不需要重新装系统对吧，还是需要加在windows里面，把efi里面的EFI / OC / OpenCore.efi加入？**冒昧问下有其他联系方式么？如果方便的话。
谢谢

**Comment by hx2nn** [comment]
> 我也想更换为OC引导，用Bootice添加了EFI / OC / OpenCore.efi启动项后，启动时显示一秒钟左右就自动启动Windows系统了，但是应该自动屏蔽了PM981硬盘的，所以启动Windows直接卡死。如何设置重置启动Mac的磁盘呢？

请问是要在pe引导里面用Bootice添加了EFI / OC / OpenCore.efi启动项么

**Comment by bluezsd** [comment]
> > 我也想更换为OC引导，用Bootice添加了EFI / OC / OpenCore.efi启动项后，启动时显示一秒钟左右就自动启动Windows系统了，但是应该自动屏蔽了PM981硬盘的，所以启动Windows直接卡死。如何设置重置启动Mac的磁盘呢？
> 
> 请问是要在pe引导里面用Bootice添加了EFI / OC / OpenCore.efi启动项么

不需要重装Mac，在Win下或者PE下用Bootice添加EFI / OC / OpenCore.efi的启动项，然后开机选择新添加的OC启动项来启动电脑，接着一直按ESC键，选择你Mac所在磁盘启动Mac，进入Mac后用启动磁盘功能改成默认mac启动。

**Comment by hx2nn** [comment]
> 然后一直按ESC键，选择你Mac所在磁盘启动Mac，

好的，谢谢。这样能跟上了，大神们加油啊

**Comment by hx2nn** [comment]
> > 电池的话你看看你的kexts里面有没有apcibatterymanager.kext，没有的话加上这个驱动，我里面有这个，我也重新替换后重新启动了，还是固定在65％
> 
> 加入这个`SSDT-PLUG-_SB.PR00.aml`到clover / acpi /已修补

按照这个方法，已经解决。感谢

**Comment by hx2nn** [comment]
> > > 电池的话你看看你的kexts里面有没有apcibatterymanager.kext，没有的话加上这个驱动，我里面有这个，我也重新替换后重新启动了，还是固定在65％
> > 
> > 
> > 加入这个`SSDT-PLUG-_SB.PR00.aml`到clover / acpi /已修补
> 
> 按照这个方法，已经解决。感谢

高兴太早，现在电池只能充电到65%就停止了

**Comment by xuejinwei** [comment]
我也遇到同样的问题，我把clover文件夹删除了，OC启动不了，是要替换OC 的相关文件吗？？
