### ISSUE TITLE
ACPI Patch

### ISSUE THREAD

**Issue by Errrneist** [hsd815/Y9000X-4K-hackintosh#7]
请问你有没有打ACPI DSDT补丁呢？如果有的话可以说一下打了什么补丁吗？

**Comment by hsd815** [comment]
> 请问你有没有打ACPI DSDT补丁呢？如果有的话可以说一下打了什么补丁吗？

打了一些改名补丁，我回头用mac看看，现在学业比较忙，都是用的win系统。。

**Comment by Errrneist** [comment]
> > 请问你有没有打ACPI DSDT补丁呢？如果有的话可以说一下打了什么补丁吗？
> 
> 打了一些改名补丁，我回头用mac看看，现在学业比较忙，都是用的win系统。。

过于真实 学业繁忙我也好久没用mac了...

**Comment by hsd815** [comment]
> > > 请问你有没有打ACPI DSDT补丁呢？如果有的话可以说一下打了什么补丁吗？
> > 
> > 
> > 打了一些改名补丁，我回头用mac看看，现在学业比较忙，都是用的win系统。。
> 
> 过于真实 学业繁忙我也好久没用mac了...

patch可以在config里面查看，都是一些更名补丁
