### ISSUE TITLE
用这个EFI无法识别USB无线网卡

### ISSUE THREAD

**Issue by bluezsd** [hsd815/Y9000X-4K-hackintosh#8]
买的DW1820A还没到，想暂时用着USB无线网卡，装了驱动后明明插了USB网卡，可是识别不了，显示没有插入，可是USB接口是正常的，插鼠标和U盘都没问题，不知道是什么原因。另外就是触摸板也是没有驱动的。
用了programbw的EFI倒是可以识别并正常使用USB无线网卡，而且触摸板也可以驱动，不过他的EFI显存只有1500M。

**Comment by hsd815** [comment]
> 买的DW1820A还没到，想暂时用着USB无线网卡，装了驱动后明明插了USB网卡，可是识别不了，显示没有插入，可是USB接口是正常的，插鼠标和U盘都没问题，不知道是什么原因。另外就是触摸板也是没有驱动的。
> 用了programbw的EFI倒是可以识别并正常使用USB无线网卡，而且触摸板也可以驱动，不过他的EFI显存只有1500M。

USB网卡是mac免驱的吗？如果不是的话要加入对应的驱动，你用clover的话也可以直接把他的驱动全复制进kexts文件夹

**Comment by bluezsd** [comment]
不是免驱的，在Mac下装个驱动然后重启就可以用的。可是装了驱动后，识别不了网卡。

**Comment by hsd815** [comment]
> 不是免驱的，在Mac下装个驱动然后重启就可以用的。可是装了驱动后，识别不了网卡。

你看一下系统加载了哪些第三方驱动，这个网卡的驱动有没有成功加载，把programbw的网卡相关的驱动复制进去就那个appleIGB、Intel开头、realtek开头的
