### ISSUE TITLE
更换DW1820A网卡导致电脑开不了机

### ISSUE THREAD

**Issue by bluezsd** [hsd815/Y9000X-4K-hackintosh#9]
黑果小兵那里买了个屏蔽了针脚的DW1820A无线网卡，换上去之后按电源键都没有任何反应，插电源也不会亮电源灯，也开不了机。换上自带的网卡后又可以正常开机。换无线网卡需要注意什么吗？你们换的时候有没有这个问题？

**Comment by hsd815** [comment]
> 黑果小兵那里买了个屏蔽了针脚的DW1820A无线网卡，换上去之后按电源键都没有任何反应，插电源也不会亮电源灯，也开不了机。换上自带的网卡后又可以正常开机。换无线网卡需要注意什么吗？你们换的时候有没有这个问题？

没有这个问题，但是你这种情况可以试着在bios里面关闭wireless那个选项
进系统了配置好驱动再打开

**Comment by hsd815** [comment]
> 黑果小兵那里买了个屏蔽了针脚的DW1820A无线网卡，换上去之后按电源键都没有任何反应，插电源也不会亮电源灯，也开不了机。换上自带的网卡后又可以正常开机。换无线网卡需要注意什么吗？你们换的时候有没有这个问题？
你应该使用了其他的EFI不是用的我这个把

**Comment by hx2nn** [comment]
我也是这个型号的网卡，小兵买的没有这种问题。自己看看针脚屏蔽有没有问题。你也可以先不装网卡，用这里的efi完成安装后再插上试试

**Comment by bluezsd** [comment]
现在可以开机了，原来需要拔了电池排线换网卡，不然会有静电保护。但是现在还有个问题，我用的是你18号的EFI，在Mac下WIFI搜不到5G信号，只能连2.4g的，而在Win10是可以连5g WIFI的，说明网卡本身没问题，蓝牙在Win和Mac都是正常的。Mac下WIFI搜不到5G的问题你们有遇到吗？

**Comment by hx2nn** [comment]
> 在Win10是可以连5g WIFI的，说明网卡本身没问题，蓝牙在Win和Mac都是正常的。Mac下WIFI搜不到5G的问题你们有遇到吗？

我也遇到过这个问题，你把你的路由器5g信道换一个就行了。不是电脑问题，是路由的问题

**Comment by bluezsd** [comment]
> > 在Win10是可以连5g WIFI的，说明网卡本身没问题，蓝牙在Win和Mac都是正常的。Mac下WIFI搜不到5G的问题你们有遇到吗？
> 
> 我也遇到过这个问题，你把你的路由器5g信道换一个就行了。不是电脑问题，是路由的问题

好，我试试看换一下5G的信道看Mac下能不能搜到并连接

**Comment by wghemail** [comment]
刚开始换1830网卡，也遇到过无法开机，换回原来的网卡也不行，重启键才开的机，换小兵的1820A直接可以用，bios先关闭了WiFi

**Comment by bluezsd** [comment]
> 刚开始换1830网卡，也遇到过无法开机，换回原来的网卡也不行，重启键才开的机，换小兵的1820A直接可以用，bios先关闭了WiFi

我的之前是更换网卡后，按电源键没有任何反应，插充电器也没有亮灯，根本进不了BIOS，后来查到是静电保护，拔掉电源排线几分钟，再插回去就好了。

**Comment by bluezsd** [comment]
> > > 在Win10是可以连5g WIFI的，说明网卡本身没问题，蓝牙在Win和Mac都是正常的。Mac下WIFI搜不到5G的问题你们有遇到吗？
> > 
> > 
> > 我也遇到过这个问题，你把你的路由器5g信道换一个就行了。不是电脑问题，是路由的问题
> 
> 好，我试试看换一下5G的信道看Mac下能不能搜到并连接

> > 在Win10是可以连5g WIFI的，说明网卡本身没问题，蓝牙在Win和Mac都是正常的。Mac下WIFI搜不到5G的问题你们有遇到吗？
> 
> 我也遇到过这个问题，你把你的路由器5g信道换一个就行了。不是电脑问题，是路由的问题

谢谢啦，修改5G信道问题就解决了。原来网卡只支持部分信道的信号，比如149、153等等，我把5G信道修改为153的就可以连接了。

**Comment by CyrilTaylor** [comment]
请问是需要屏蔽前三还是后二，还是五个脚都要屏蔽？自己买的DW1820A，小兵的断货了

**Comment by hsd815** [comment]
全部都屏蔽
&nbsp;

侯绍冬
Hou Shaodong
华中科技大学-武汉光电国家实验室&nbsp;&nbsp;
Wuhan National Laboratory for Optoelectronics/HUST
&nbsp;电话：13072747371
TEL：13072747371
地址：湖北省武汉市珞瑜路1037号华中科技大学南五楼南114室，430074
ADD：1037 Luoyu Road, Wuhan, Hubei, P.R.China,&nbsp;430074


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Cyril Taylor"<notifications@github.com&gt;; 
发送时间: 2020年4月3日(星期五) 下午2:16
收件人: "hsd815/Y9000X-4K-hackintosh"<Y9000X-4K-hackintosh@noreply.github.com&gt;; 
抄送: "Hust.Hou"<815113385@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [hsd815/Y9000X-4K-hackintosh] 更换DW1820A网卡导致电脑开不了机 (#9)





 
请问是需要屏蔽前三还是后二，还是五个脚都要屏蔽？自己买的DW1820A，小兵的断货了

**Comment by hsd815** [comment]
> 请问是需要屏蔽前三还是后二，还是五个脚都要屏蔽？自己买的DW1820A，小兵的断货了

全部都屏蔽
